customhost = "employee-db.cfm02hoyzddn.us-east-1.rds.amazonaws.com"
customuser = "Saurabh27432Demo"
custompass = "Paratesaurabh"
customdb = "employee"
custombucket = "bucketcancontain"
customregion = "us-east-1"
